arb-dir: l10n # Директория, где хранятся файлы переводов
template-arb-file: app_ru.arb # Файл-шаблон, где описываются параметры строк
output-localization-file: app_localizations.dart # Сгенерированный файл локализации
nullable-getter: false